axis_linear:
 x: 4  # Right thumb stick vertical
 y: 0  # Left thumb stick horizontal

scale_linear:
 x: 0.5
 y: 0.4


axis_angular: 3  # Right thumb stick horizontal
scale_angular: 0.4

enable_button: 4  # Left bumper button
